project_name: "single_agent_experiment"
sub_project_name: "training"
experiment_name: "conv_lstm_mse_det_loss"
seed: 42

data:
  data_path: "data/physics_single_agent_train"
  batch_size: 32

loss:
  name: "mse"

model:
  type: "conv_lstm"
  is_probabilistic: false
  h_ctx: 5
  h_pred: 5
  hidden_dim: 32
  n_layers: 3
  kernel_size: 5

checkpoint:
  monitor: "val_loss"

optimizer:
  max_epochs: 500
