project_name: "single_agent_experiment"
sub_project_name: "training"
experiment_name: "fno_mse_det_loss"
seed: 42

data:
  data_path: "data/physics_single_agent_train"

loss:
  name: "mse"

model:
  type: "fno"
  is_probabilistic: false
