# Configuration for physical smoke data generation
# All unspecified parameters will use the default values from DataCollectionConfig.

num_episodes: 100
output_path: "data/structured_single_agent_env"

test: True

# If you wish to override any default value, do it here. Example:
smoke_params:
  x_size: 30.0
  y_size: 20.0
  average_wind_speed: 8.0
  smoke_decay_rate: 1.5
  smoke_emission_rate: 2.0
  smoke_diffusion_rate: 0.0
  inflow_bank_count: 5
  buoyancy_factor: 1.2
