run:
  episodes: 100
  steps: null
  device: null
  controllers: null
  output_dir: null
  render: "none"
  test: false

agent:
  name: "dubins2d"
  action_min: [0.0, -4.0]
  action_max: [6.0, 4.0]
  action_dim: 2
  state_dim: 3
  state_min: [0.0, 0.0, 0.0]
  state_max: [35.0, 35.0, 6.28318530718]
  dt: 0.1
  device: "cpu"

env:
  num_agents: 6
  world_x_size: 35.0
  world_y_size: 35.0
  clock: 0.1
  max_steps: 1000
  collision_radius: 0.8
  goal_radius: 1.2
  render: "rgb_array"
  render_save_every: 1
  terminate_on_collision: false
  collision_penalty: 10.0
  smoke_density_threshold: 0.5
  save_transitions: false
  # Coordenadas cruzadas
  initial_locations:
    - [3.0, 5.0]
    - [3.0, 17.5]
    - [3.0, 30.0]
    - [32.0, 5.0]
    - [32.0, 17.5]
    - [32.0, 30.0]
  goal_locations:
    - [32.0, 30.0]
    - [32.0, 17.5]
    - [32.0, 5.0]
    - [3.0, 30.0]
    - [3.0, 17.5]
    - [3.0, 5.0]

sensor:
  sensor_type: "global"
  density_reading_per_unit_length: 0.0

playback:
  # Ruta a los datos de la simulación base a reproducir
  data_path: "data/smoke_env_100ep" # "/data/emunoz/hf_datasets/physics_base"

# Diccionario de controladores. Configuraciones minimalistas gracias al polimorfismo y defaults del core.
controllers:
  nominal:
    type: "nominal"
    mppi:
      horizon: 20
      num_samples: 200

  cbf_filter:
    type: "cbf"
    mode: "filter"
    k1: 5.0
    k2: 1.0
    rho: 1.0
    L: 1.0
    safety:
      safe_margin: 0.5
      r_sense: 5.0
    mppi:
      horizon: 20
      num_samples: 200

  cbf_dual_guard:
    type: "cbf"
    mode: "dual-guard"
    k1: 5.0
    k2: 1.0
    rho: 1.0
    L: 1.0
    safety:
      safe_margin: 0.5
      r_sense: 5.0
    mppi:
      horizon: 20
      num_samples: 200

  cbf_penalty:
    type: "cbf"
    mode: "penalty"
    k1: 5.0
    k2: 1.0
    rho: 1.0
    L: 1.0
    safety:
      safe_margin: 0.5
      r_sense: 5.0
    mppi:
      horizon: 20
      num_samples: 200

  hj_filter:
    type: "hj"
    mode: "filter"
    control_type: "bang_bang"
    safety:
      safe_margin: 0.5
      r_sense: 5.0
    solver:
      interaction_radius: 5.0
      spatial_resolution: 0.196
      angular_cells: 51
      target_time: 1.5
      dt: 0.1
      superlevel_set_epsilon: 0.2
      safe_margin: 0.2
    mppi:
      horizon: 20
      num_samples: 200

  hj_dual_guard:
    type: "hj"
    mode: "dual-guard"
    control_type: "bang_bang"
    safety:
      safe_margin: 0.5
      r_sense: 5.0
    solver:
      interaction_radius: 5.0
      spatial_resolution: 0.196
      angular_cells: 51
      target_time: 1.5
      dt: 0.1
      superlevel_set_epsilon: 0.2
      safe_margin: 0.2
    mppi:
      horizon: 20
      num_samples: 200

  hj_online_dual_guard:
    type: "hj"
    mode: "online_dual-guard"
    control_type: "bang_bang"
    safety:
      safe_margin: 0.5
      r_sense: 5.0
    solver:
      interaction_radius: 5.0
      spatial_resolution: 0.196
      angular_cells: 51
      target_time: 1.5
      dt: 0.1
      superlevel_set_epsilon: 0.2
      safe_margin: 0.2
    mppi:
      horizon: 20
      num_samples: 200

  hj_penalty:
    type: "hj"
    mode: "penalty"
    control_type: "bang_bang"
    safety:
      safe_margin: 0.5
      r_sense: 5.0
    solver:
      interaction_radius: 5.0
      spatial_resolution: 0.196
      angular_cells: 51
      target_time: 1.5
      dt: 0.1
      superlevel_set_epsilon: 0.2
      safe_margin: 0.2
    mppi:
      horizon: 20
      num_samples: 200
