# Configuration for physical smoke data generation
# All unspecified parameters will use the default values from DataCollectionConfig.

num_episodes: 500
output_path: "data/physics_single_agent_train"

test: True

# If you wish to override any default value, do it here. Example:
# smoke_params:
#   average_wind_speed: 10.0
