project_name: "single_agent_experiment"
sub_project_name: "integration"
experiment_mode: cbf

env:
  num_agents: 1
  clock: 0.1
  save_transitions: true
  save_global_map_transitions: false
  render: "rgb_array"
  initial_locations: [[2.0, 10.0]]
  goal_locations: [[28.0, 10.0]]


simulator:
  data_path: "data/structured_single_agent_env"

sensor:
  sensor_type: "global"

cbf:
  smoke_threshold: 0.6
  discrete_epsilon: 0.5
