project_name: "single_agent_experiment"
sub_project_name: "integration"
experiment_mode: fno

env:
  num_agents: 1
  clock: 0.1
  save_transitions: true
  render: "rgb_array"
  initial_locations: [[2.0, 10.0]]
  goal_locations: [[28.0, 10.0]]


simulator:
  data_path: "data/structured_single_agent_env"

sensor:
  sensor_type: "global"

mppi:
  nx: 3
  alpha_noise_sigma: 1.0
  num_samples: 100
  horizon: 20
  u_min: [0.0, -4.0]
  u_max: [6.0, 4.0]
  device: "cuda"

fno_checkpoint: "outputs/single_agent_experiment/training/fno_nll_loss/2026-07-01/10-09-25/checkpoints/last.ckpt"
fno_config: "outputs/single_agent_experiment/training/fno_nll_loss/2026-07-01/10-09-25/config_used.yaml"
